service:
  name: drift-python-demo
  port: 3000
  start:
    command: python server.py
  readiness_check:
    command: curl -fsS http://localhost:3000/health
    timeout: 30s
    interval: 1s
  id: d02e3f3f-f1f0-4786-b0eb-5159261ee3c8

traces:
  dir: .tusk/traces

test_execution:
  timeout: 30s

recording:
  sampling_rate: 1 # Record 100% of requests
  export_spans: true # Export spans to cloud
  enable_env_var_recording: false

tusk_api:
  url: https://use-tusk-dev.uc.r.appspot.com

# Only recording traces locally, API url not needed
# tusk_api:
#     url: https://api.usetusk.ai
